services:
  gateway:
    image: sergeimlk/tp-microservices-gateway:latest
    ports:
      - "3002:3002"
    depends_on:
      - music-service
      - game-service
    networks:
      - app-network

  game-service:
    image: sergeimlk/tp-microservices-jeux:latest
    networks:
      - app-network

  music-service:
    image: sergeimlk/tp-microservices-musique:latest
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
