name: CI/CD Docker & VPS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Gateway
        uses: docker/build-push-action@v5
        with:
          context: ./gateway
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-microservices-gateway:latest

      - name: Build and Push Music Service
        uses: docker/build-push-action@v5
        with:
          context: ./service-musique
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-microservices-musique:latest

      - name: Build and Push Game Service
        uses: docker/build-push-action@v5
        with:
          context: ./service-jeux
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-microservices-jeux:latest

  deploy-to-vps:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }} # Plus simple que la clé SSH
          port: 22
          script: |
            # On va dans le dossier root (ou là où est le docker-compose.yml)
            cd /root
            
            # On récupère les dernières images
            docker compose pull
            
            # On relance les conteneurs
            docker compose up -d