name: CI/CD Docker & VPS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Gateway
        uses: docker/build-push-action@v5
        with:
          context: ./gateway
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-microservices-gateway:latest

      - name: Build and Push Music Service
        uses: docker/build-push-action@v5
        with:
          context: ./service-musique
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-microservices-musique:latest

      - name: Build and Push Game Service
        uses: docker/build-push-action@v5
        with:
          context: ./service-jeux
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-microservices-jeux:latest

  deploy-to-vps:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }} # Plus simple que la clé SSH
          port: 22
          script: |
            # Créer le contenu du docker-compose.prod.yml directement
            cat <<EOF > /root/docker-compose.yml
            services:
              gateway:
                image: ${{ secrets.DOCKERHUB_USERNAME }}/tp-microservices-gateway:latest
                ports:
                  - "3002:3002"
                depends_on:
                  - music-service
                  - game-service
                networks:
                  - app-network

              game-service:
                image: ${{ secrets.DOCKERHUB_USERNAME }}/tp-microservices-jeux:latest
                networks:
                  - app-network

              music-service:
                image: ${{ secrets.DOCKERHUB_USERNAME }}/tp-microservices-musique:latest
                networks:
                  - app-network

            networks:
              app-network:
                driver: bridge
            EOF
            
            # On récupère les dernières images
            docker compose pull
            
            # On relance les conteneurs (avec --force-recreate pour être sûr)
            docker compose up -d --force-recreate